mode = "dark"

accent = "#dda13b"
selection = "#49351f"
muted = "#92856c"

background = "#26231b"
dark_background = "#191810"
darker_background = "#0f0e0b"
lighter_background = "#302c22"

foreground = "#d4cab2"
dark_foreground = "#918871"
light_foreground = "#e2d8bf"
bright_foreground = "#eee5ce"

red = "#c85e40"
yellow = "#dfac42"
orange = "#dda13b"
green = "#a3a752"
cyan = "#8da18a"
blue = "#899897"
magenta = "#b17a66"
brown = "#765238"

bright_red = "#e27653"
bright_yellow = "#edc256"
bright_green = "#bbc366"
bright_cyan = "#a6b9a3"
bright_blue = "#a0aeaa"
bright_magenta = "#c68e78"

hyprland_active_border = "rgba(dda13bff)"
hyprland_inactive_border = "rgba(514b3fbb)"
