mode = "dark"

accent = "#d7802f"
selection = "#49351f"
muted = "#827660"

background = "#151816"
dark_background = "#101310"
darker_background = "#0b0e0c"
lighter_background = "#20251f"

foreground = "#d1d4c8"
dark_foreground = "#8d9587"
light_foreground = "#e0e2d8"
bright_foreground = "#f0f1e6"

red = "#d65b3e"
yellow = "#dfae3b"
orange = "#d7802f"
green = "#9aaa4b"
cyan = "#78a38c"
blue = "#779397"
magenta = "#ae7166"
brown = "#785136"

bright_red = "#ed7653"
bright_yellow = "#edc34f"
bright_green = "#b0c45a"
bright_cyan = "#8bb89b"
bright_blue = "#8aa8aa"
bright_magenta = "#c18475"
